[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

[common]
lib_deps =
    paulstoffregen/Audio
    https://github.com/PaulStoffregen/Audio.git
    https://github.com/PaulStoffregen/Audio.git#master
    SD
    SPI
    Wire
    https://github.com/me-no-dev/ESPAsyncTCP.git
    knolleary/PubSubClient@^2.8
    paulstoffregen/OneWire
